CREATE DATABASE StudyManagementApp
GO

USE StudyManagementApp
GO

CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(100) PRIMARY KEY,
	PASSWORD VARCHAR(100)
)
GO

INSERT INTO ACCOUNT VALUES ('staff', '123456')

CREATE PROC USP_GetAccountByUserName
@userName NVARCHAR(100)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @userName
END
GO

EXEC USP_GetAccountByUserName @userName = N'staff'

SELECT * FROM ACCOUNT WHERE USERNAME = 'staff' AND PASSWORD = '123'
GO

CREATE PROC USP_Login
@userName NVARCHAR(100), @passWord NVARCHAR(100)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @userName AND PASSWORD = @passWord
END
GO

CREATE PROC USP_Signup
@userName NVARCHAR(100), @passWord NVARCHAR(100)
AS
BEGIN
	INSERT INTO ACCOUNT(USERNAME, PASSWORD) VALUES (@userName, @passWord)
END
GO