CREATE DATABASE StudyManagementApp3
GO

USE StudyManagementApp3
GO

CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(100) PRIMARY KEY,
	PASSWORD VARCHAR(100)
)
GO

ALTER TABLE ACCOUNT ADD EMAIL VARCHAR(100)

CREATE PROC USP_Login
@userName NVARCHAR(100), @passWord NVARCHAR(100)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @userName AND PASSWORD = @passWord
END
GO

CREATE PROC USP_Signup
@userName NVARCHAR(100), @passWord NVARCHAR(100), @email VARCHAR(100)
AS
BEGIN
	INSERT INTO ACCOUNT(USERNAME, PASSWORD, EMAIL) VALUES (@userName, @passWord, @email)
END
GO

CREATE PROC USP_ChangePassword
@username NVARCHAR(100), @newPassowrd NVARCHAR(100)
AS
BEGIN
	UPDATE ACCOUNT
	SET PASSWORD=@newPassowrd
	WHERE USERNAME=@username
END
GO

CREATE PROC USP_VerifyUserExist
@userName NVARCHAR(100)
AS
BEGIN
	SELECT USERNAME FROM ACCOUNT WHERE USERNAME = @userName
END
GO

CREATE PROC USP_VerifyEmailExist
@email VARCHAR(100)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE EMAIL = @email
END
GO

CREATE PROC USP_EmailOfEachUser
@userName VARCHAR(100), @email VARCHAR(100)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @userName AND EMAIL = @email
END
GO
--CREATE PROC USP_GetAccountByUserName
--@userName NVARCHAR(100)
--AS
--BEGIN
--	SELECT * FROM ACCOUNT WHERE USERNAME = @userName
--END
--GO

--EXEC USP_GetAccountByUserName @userName = N'staff'

--SELECT * FROM ACCOUNT WHERE USERNAME = 'staff' AND PASSWORD = '123'
--GO

