USE StudyManagementApp

CREATE TABLE DECK
(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NAME NVARCHAR(255),
	USERNAME VARCHAR(100)
)
GO

ALTER TABLE DECK ADD CONSTRAINT FK_DECK_USERNAME FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME)
GO

CREATE TABLE FLASHCARD
(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DECKID INT,
	WORD NVARCHAR(255),
	DEFINITION NVARCHAR(255),
	DESCRIPTION NVARCHAR(2048)
)
GO

ALTER TABLE FLASHCARD ADD CONSTRAINT FK_FLASHCARD_DECKID FOREIGN KEY (DECKID) REFERENCES DECK(ID)
GO

CREATE PROCEDURE GetDecks
@username VARCHAR(100)
AS
BEGIN
	SELECT ID, NAME FROM DECK WHERE USERNAME=@username
END
GO

CREATE PROCEDURE GetFlashCards
@deckID INT
AS
BEGIN
	SELECT ID, WORD, DEFINITION, DESCRIPTION FROM FLASHCARD WHERE DECKID=@deckID
END
GO

CREATE PROCEDURE InsertDeck
@username VARCHAR(100), @name NVARCHAR(255)
AS
BEGIN
	INSERT INTO DECK(USERNAME, NAME) VALUES (@username, @name)
END
GO

CREATE PROCEDURE DeleteDeck
@deckID INT
AS
BEGIN
	DELETE FROM DECK WHERE ID=@deckID
END
GO

CREATE PROCEDURE UpdateDeck
@deckID INT, @name NVARCHAR(255)
AS
BEGIN
	UPDATE DECK
	SET NAME=@name
	WHERE ID=@deckID
END
GO

CREATE PROCEDURE InsertFlashCard
@deckID INT, @word NVARCHAR(255), @definition NVARCHAR(255), @description NVARCHAR(2048)
AS
BEGIN
	INSERT INTO FLASHCARD(DECKID, WORD, DEFINITION, DESCRIPTION) VALUES (@deckID, @word, @definition, @description)
END
GO

CREATE PROCEDURE DeleteFlashCard
@id INT
AS
BEGIN
	DELETE FROM FLASHCARD WHERE ID=@id
END
GO

CREATE PROCEDURE UpdateFlashCard
@id INT, @word NVARCHAR(255), @definition NVARCHAR(255), @description NVARCHAR(2048)
AS
BEGIN
	UPDATE FLASHCARD
	SET WORD=@word, DEFINITION=@definition, DESCRIPTION=@description
	WHERE ID=@id
END
GO
