use StudyManagementApp3
go

CREATE TABLE TASK(
	USERNAME VARCHAR(100),
	DATECREATE DATE,
	DESCIPTION VARCHAR(100),
	TIMESTART DATETIME,
	TIMEEND DATETIME,
	DONE VARCHAR(10),
	PRIMARY KEY(USERNAME,DATECREATE,DESCIPTION)
)
GO

ALTER TABLE TASK ADD CONSTRAINT FK_TASK_USERNAME FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME)
GO